language: python

install:
- echo "pytest-cov<=2.9.0" >> requirements.txt
- echo pytest-django >> requirements.txt
- pip install -r requirements.txt
- pip install django$DJANGO_VERSION
- pip install -e .
script: pytest --cov-report=xml --cov=qiniustorage tests/ --verbose --capture=no

matrix:
  include:
    - env: DJANGO_VERSION=">=3"
      python: "3.7"
    - env: DJANGO_VERSION=">=3"
      python: "3.8"
    - env: DJANGO_VERSION="<3"
      python: "3.5"
    - env: DJANGO_VERSION="<3"
      python: "3.7"
    - env: DJANGO_VERSION="<3"
      python: "3.8"


 # You need to configure QINIU_BUCKET_NAME, QINIU_BUCKET_DOMAIN, QINIU_PRIVATE_BUCKET_NAME, QINIU_PRIVATE_BUCKET_DOMAIN, QINIU_ACCESS_KEY and QINIU_SECRET_KEY in Travis.

env:
  global:
  - USING_TRAVIS=YES
